# Generated by Django 3.0.5 on 2020-05-08 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativoreceitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='cozinheiro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
