# Generated by Django 3.0.5 on 2020-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativoreceitas', '0003_receita_modo_edicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem_receita',
            field=models.ImageField(blank=True, upload_to='imagens/%d/%m/%Y/'),
        ),
    ]
